DROP TABLE IF EXISTS COMPOSITE_BATCH_BEANS;

CREATE TABLE `COMPOSITE_BATCH_BEANS` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(255) NOT NULL,
	`JOB_NAME` VARCHAR(255) NOT NULL,
	`BATCH_BEAN_TYPE` VARCHAR(50) NULL DEFAULT NULL,
	`PRIORITY` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`)
);
