name: Spring Batch BigQuery

on:
  pull_request:
    paths:
      - 'spring-batch-bigquery/**'
  push:
    paths:
      - 'spring-batch-bigquery/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package
        working-directory: spring-batch-bigquery
